server:
  port: 8080
spring:
  application:
    name: "CrediYaRequests"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
adapters:
  r2dbc:
    host: "localhost"
    port: 49153
    database: "postgres"
    schema: "public"
    username: "postgres"
    password: "postgrespw"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-doc